### ISSUE TITLE
Projecting 3D labels from point cloud to 3D labels in range image

### ISSUE THREAD

**Issue by NEURALWORKS91** [gdlg/simple-waymo-open-dataset-reader#3]
Hi,
I have tried the 3D box projection from point cloud labels to camera images and it works.
But, I wish to do object detection using range images and hence want to generate 3D labels in the range image, using the labels from the point cloud.
Is this possible?
In other words, can I take a box label in the point cloud and get the same object in the corresponding in the range image and then draw a bounding box around it?
Please explain with a short code if possible.
Best Regards
Sambit

**Comment by gdlg** [comment]
Hi,
See my response to issue #2 which you opened earlier. I don’t have the time to write and test code for you however if you take inspiration from the links that I have included, it shouldn’t be too difficult to do what you want.
