### ISSUE TITLE
open3d 0.9.0.0 error

### ISSUE THREAD

**Issue by jingyibo123** [gdlg/simple-waymo-open-dataset-reader#7]
Hi everyone,

Thanks for sharing!
Just a head up, the newest open3d 0.9.0.0 in pip leads to the error below, after switching back to 0.8.0.0 all works

Maybe update the requirements.txt ?

> Traceback (most recent call last):
  File "examples/visualise_pcl.py", line 83, in <module>
    display_next_frame()
  File "examples/visualise_pcl.py", line 78, in display_next_frame
    vis.update_geometry()
TypeError: update_geometry(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.open3d.visualization.Visualizer, arg0: open3d.open3d.geometry.Geometry) -> bool

Yibo

**Comment by gdlg** [comment]
Hi @jingyibo123, thanks for reporting. I will have a look to upgrade the code to the latest open3d.

**Comment by gdlg** [comment]
Thanks @jingyibo123 , I have updated the example to work with the latest Open3D.
